const zeroButton = document.getElementById("zero")
const oneButton = document.getElementById("one")
const twoButton = document.getElementById("two")
const threeButton = document.getElementById("three")
const fourButton = document.getElementById("four")
const fiveButton = document.getElementById("five")
const sixButton = document.getElementById("six")
const sevenButton = document.getElementById("seven")
const eightButton = document.getElementById("eight")
const nineButton = document.getElementById("nine")
const addButton = document.getElementById("add")
const subButton = document.getElementById("sub")
const multButton = document.getElementById("mult")
const divButton = document.getElementById("div")
const ansButton = document.getElementById("ans")

